import 'dart:io';
import 'package:envault_cli/src/crypto/aes_gcm_encryptor.dart';

/// Generates the vault.g.dart file from encrypted secrets.
///
/// KEY SECURITY PROPERTIES OF GENERATED CODE:
/// 1. The master password is NEVER a string literal in generated code.
///    It is read via String.fromEnvironment('VAULT_MASTER_PASSWORD') which is
///    compiled as a constant baked in by --dart-define at flutter build time.
///
/// 2. A password fingerprint is embedded. At app startup, assertVaultPassword()
///    computes the same fingerprint from the runtime password and compares.
///    A mismatch (password used to build ≠ password used to generate) is caught
///    before any decryption is attempted, giving a clear error message.
///
/// 3. Ciphertext, IV, and GCM auth tags are embedded as const byte arrays.
///    Without the correct master password, they are mathematically opaque.
class DartCodeEmitter {
  static Future<void> generate({
    required String outputPath,
    required String className,
    required String kid,
    required String packageName,
    required String buildFlavor,
    required String passwordFingerprint,
    required Map<String, EncryptedSecret> secrets,
  }) async {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED BY envault CLI — DO NOT EDIT');
    buffer.writeln('// KID: $kid');
    buffer.writeln('// Password fingerprint: $passwordFingerprint (first 8 bytes of HMAC-SHA256)');
    buffer.writeln('// WARNING: Commit this file — it contains only ciphertext, never plaintext.');
    buffer.writeln('// Run "envault generate" to regenerate after changing .env or rotating password.');
    buffer.writeln('// ignore_for_file: non_constant_identifier_names, unused_field, unused_element, invalid_use_of_internal_member');
    buffer.writeln();
    buffer.writeln("part of 'vault.dart';");
    buffer.writeln();

    // Helper
    String formatBytes(List<int> bytes) {
      return '[' +
          bytes
              .map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}')
              .join(', ') +
          ']';
    }

    buffer.writeln('final class _$className {');
    buffer.writeln('  // Key derivation parameters (non-secret AAD components)');
    buffer.writeln("  static const String _kid = '$kid';");
    buffer.writeln("  static const String _packageName = '$packageName';");
    buffer.writeln("  static const String _buildFlavor = '$buildFlavor';");
    buffer.writeln();
    buffer.writeln('  // Password fingerprint — first 8 bytes of HMAC-SHA256(password, "ENVAULT_FINGERPRINT_V1").');
    buffer.writeln('  // Used by assertVaultPassword() to detect a password mismatch at app startup.');
    buffer.writeln('  // This is NOT the master password and cannot be reversed to recover it.');
    buffer.writeln("  static const String _passwordFingerprint = '$passwordFingerprint';");
    buffer.writeln();

    for (final entry in secrets.entries) {
      final fieldName = entry.key;
      final secret = entry.value;

      buffer.writeln('  // Encrypted field: $fieldName');
      buffer.writeln(
          '  static final Uint8List _${fieldName}_iv = Uint8List.fromList(const ${formatBytes(secret.iv)});');
      buffer.writeln(
          '  static final Uint8List _${fieldName}_tag = Uint8List.fromList(const ${formatBytes(secret.tag)});');
      buffer.writeln(
          '  static final Uint8List _${fieldName}_ct = Uint8List.fromList(const ${formatBytes(secret.ciphertext)});');
      buffer.writeln('  static SecureString? _${fieldName}_cache;');
      buffer.writeln();
      buffer.writeln('  static SecureString get $fieldName {');
      buffer.writeln('    return _${fieldName}_cache ??= SecureString(');
      buffer.writeln('      ciphertext: _${fieldName}_ct,');
      buffer.writeln('      iv: _${fieldName}_iv,');
      buffer.writeln('      tag: _${fieldName}_tag,');
      buffer.writeln("      fieldName: '$fieldName',");
      buffer.writeln('      kid: _kid,');
      buffer.writeln('      packageName: _packageName,');
      buffer.writeln('      decryptor: _decrypt,');
      buffer.writeln('    );');
      buffer.writeln('  }');
      buffer.writeln();
    }

    // Derived key cache
    buffer.writeln('  static Uint8List? _cachedKey;');
    buffer.writeln();

    // assertVaultPassword — the mismatch detector
    buffer.writeln('  /// Verifies the VAULT_MASTER_PASSWORD baked into this binary matches');
    buffer.writeln('  /// the password used when running "envault generate".');
    buffer.writeln('  ///');
    buffer.writeln('  /// Call this once in main() before runApp():');
    buffer.writeln('  ///   await assertVaultPassword();');
    buffer.writeln('  ///');
    buffer.writeln('  /// Throws [VaultConfigurationException] if:');
    buffer.writeln('  ///   - VAULT_MASTER_PASSWORD was not set via --dart-define at build time.');
    buffer.writeln('  ///   - The password used in flutter build differs from the one used in envault generate.');
    buffer.writeln('  static Future<void> assertVaultPassword() async {');
    buffer.writeln("    const masterPassword = String.fromEnvironment('VAULT_MASTER_PASSWORD');");
    buffer.writeln('    if (masterPassword.isEmpty) {');
    buffer.writeln('      throw VaultConfigurationException(');
    buffer.writeln("        'VAULT_MASTER_PASSWORD is not set.\\n'");
    buffer.writeln("        'Build your app with:\\n'");
    buffer.writeln("        '  flutter run --dart-define=VAULT_MASTER_PASSWORD=<YOUR_SECRET>\\n'");
    buffer.writeln("        '  flutter build apk --dart-define=VAULT_MASTER_PASSWORD=<YOUR_SECRET>\\n'");
    buffer.writeln("        'Run \"envault keygen\" to generate a secure password.',");
    buffer.writeln('      );');
    buffer.writeln('    }');
    buffer.writeln('    final hmac = Hmac.sha256();');
    buffer.writeln('    final mac = await hmac.calculateMac(');
    buffer.writeln("      utf8.encode(masterPassword),");
    buffer.writeln("      secretKey: SecretKey(utf8.encode('ENVAULT_FINGERPRINT_V1')),");
    buffer.writeln('    );');
    buffer.writeln('    final runtimeFingerprint = mac.bytes');
    buffer.writeln('        .take(8)');
    buffer.writeln("        .map((b) => b.toRadixString(16).padLeft(2, '0'))");
    buffer.writeln('        .join();');
    buffer.writeln('    if (runtimeFingerprint != _passwordFingerprint) {');
    buffer.writeln('      throw VaultConfigurationException(');
    buffer.writeln("        'VAULT_MASTER_PASSWORD mismatch detected.\\n'");
    buffer.writeln("        'The password used in \"flutter build\" differs from the one used in \"envault generate\".\\n'");
    buffer.writeln("        'Fix: Run \"envault generate\" and \"flutter build\" with the SAME VAULT_MASTER_PASSWORD.\\n'");
    buffer.writeln("        'Expected fingerprint: \$_passwordFingerprint, Got: \$runtimeFingerprint',");
    buffer.writeln('      );');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();

    // Key derivation
    buffer.writeln('  static Future<Uint8List> _getDerivedKey() async {');
    buffer.writeln('    if (_cachedKey != null) return _cachedKey!;');
    buffer.writeln();
    buffer.writeln('    // VAULT_MASTER_PASSWORD is injected at compile time via --dart-define.');
    buffer.writeln('    // It is NEVER a string literal in source code or version control.');
    buffer.writeln("    const masterPassword = String.fromEnvironment('VAULT_MASTER_PASSWORD');");
    buffer.writeln();
    buffer.writeln('    // assertVaultPassword() in main() would have already caught an empty/wrong');
    buffer.writeln('    // password. This is a defensive guard for the lazy-decryption path.');
    buffer.writeln('    if (masterPassword.isEmpty) {');
    buffer.writeln('      throw VaultConfigurationException(');
    buffer.writeln("        'VAULT_MASTER_PASSWORD is not set. '");
    buffer.writeln("        'Build with --dart-define=VAULT_MASTER_PASSWORD=<YOUR_SECRET>.',");
    buffer.writeln('      );');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    // Offload to OS-native crypto (CryptoKit/java.security) via cryptography_flutter.');
    buffer.writeln('    // 310,000 iterations of PBKDF2-HMAC-SHA256 per NIST SP 800-132 (2023 guidance).');
    buffer.writeln('    // This runs on a native thread — the Flutter UI thread is NOT blocked.');
    buffer.writeln('    final crypto = Cryptography.instance;');
    buffer.writeln('    final pbkdf2 = crypto.pbkdf2(');
    buffer.writeln('      macAlgorithm: Hmac.sha256(),');
    buffer.writeln('      iterations: 310000,');
    buffer.writeln('      bits: 256,');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    final saltInput = "\$_packageName|\$_buildFlavor|\$_kid";');
    buffer.writeln('    final saltHash = await crypto.sha256().hash(utf8.encode(saltInput));');
    buffer.writeln('    final salt = Uint8List.fromList(saltHash.bytes);');
    buffer.writeln();
    buffer.writeln('    final secretKey = await pbkdf2.deriveKey(');
    buffer.writeln('      secretKey: SecretKey(utf8.encode(masterPassword)),');
    buffer.writeln('      nonce: salt,');
    buffer.writeln('    );');
    buffer.writeln('    _cachedKey = Uint8List.fromList(await secretKey.extractBytes());');
    buffer.writeln('    return _cachedKey!;');
    buffer.writeln('  }');
    buffer.writeln();

    // Decryptor
    buffer.writeln('  static Future<String> _decrypt(');
    buffer.writeln('    Uint8List ciphertext,');
    buffer.writeln('    Uint8List iv,');
    buffer.writeln('    Uint8List tag,');
    buffer.writeln('    String fieldName,');
    buffer.writeln('    String kid,');
    buffer.writeln('    String packageName,');
    buffer.writeln('  ) async {');
    buffer.writeln('    final key = await _getDerivedKey();');
    buffer.writeln('    final algorithm = AesGcm.with256bits(nonceLength: 12);');
    buffer.writeln('    final secretKey = SecretKey(key);');
    buffer.writeln('    final aad = utf8.encode(fieldName);');
    buffer.writeln('    final secretBox = SecretBox(ciphertext, nonce: iv, mac: Mac(tag));');
    buffer.writeln('    try {');
    buffer.writeln(
        '      final decryptedBytes = await algorithm.decrypt(secretBox, secretKey: secretKey, aad: aad);');
    buffer.writeln('      return utf8.decode(decryptedBytes);');
    buffer.writeln('    } catch (e) {');
    buffer.writeln(
        "      throw VaultDecryptionException('AES-GCM decryption failed for field \"\$fieldName\". "
        "This typically means the master password is wrong or the ciphertext has been tampered with.');");
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('/// Top-level function — call once in main() before runApp().');
    buffer.writeln('///');
    buffer.writeln('/// Detects a password mismatch between:');
    buffer.writeln('///   - The password used in "envault generate" (stored as fingerprint in this file)');
    buffer.writeln('///   - The password baked in via --dart-define=VAULT_MASTER_PASSWORD at build time');
    buffer.writeln('///');
    buffer.writeln('/// Example:');
    buffer.writeln('///   void main() async {');
    buffer.writeln('///     await assertVaultPassword();   // crashes clearly if mismatch');
    buffer.writeln('///     runApp(const MyApp());');
    buffer.writeln('///   }');
    buffer.writeln('Future<void> assertVaultPassword() => _${className}.assertVaultPassword();');

    // Atomic write
    final tempFile = File('$outputPath.tmp');
    await tempFile.writeAsString(buffer.toString());
    await tempFile.rename(outputPath);
  }
}
