// GENERATED BY envault CLI — DO NOT EDIT
// Generated: 2026-06-13T11:25:09.768396Z
// KID: v1
// WARNING: Commit this file only if your .env file is gitignored
// ignore_for_file: non_constant_identifier_names, unused_field, unused_element, invalid_use_of_internal_member

part of 'vault.dart';

final class _Vault {
  // Key derivation parameters (non-secret)
  static const String _kid = 'v1';
  static const String _packageName = 'app';
  static const String _buildFlavor = 'prod';

  // Field: apiKey
  static final Uint8List _apiKey_iv = Uint8List.fromList(const [0x07, 0x83, 0x21, 0x61, 0x52, 0x59, 0x65, 0xed, 0xeb, 0x76, 0x12, 0xe2]);
  static final Uint8List _apiKey_tag = Uint8List.fromList(const [0x40, 0x86, 0x44, 0xd6, 0x56, 0xb3, 0xe5, 0xd4, 0x06, 0x2a, 0x6f, 0x9e, 0xb7, 0x5c, 0x82, 0x86]);
  static final Uint8List _apiKey_ct = Uint8List.fromList(const [0x36, 0x1b, 0x5c, 0x07, 0xf2, 0x44, 0xd5, 0xa6, 0x84, 0xef, 0xa6, 0x04, 0x90, 0x62, 0x0b, 0x78, 0x18, 0xf0, 0x24, 0xcd, 0xb6, 0x47, 0xfe, 0x0d, 0x70, 0xca, 0xed]);
  static SecureString? _apiKey_cache;

  static SecureString get apiKey {
    return _apiKey_cache ??= SecureString(
      ciphertext: _apiKey_ct,
      iv: _apiKey_iv,
      tag: _apiKey_tag,
      fieldName: 'apiKey',
      kid: _kid,
      packageName: _packageName,
      decryptor: _decrypt,
    );
  }

  // Field: anotherKey
  static final Uint8List _anotherKey_iv = Uint8List.fromList(const [0x43, 0x3d, 0x7c, 0xf4, 0x21, 0x6e, 0xa0, 0x33, 0x45, 0x0c, 0x43, 0x1f]);
  static final Uint8List _anotherKey_tag = Uint8List.fromList(const [0xbf, 0x23, 0x97, 0xf1, 0x80, 0xca, 0x3f, 0xc2, 0x11, 0x91, 0xf6, 0xc3, 0x00, 0x89, 0xb2, 0xcc]);
  static final Uint8List _anotherKey_ct = Uint8List.fromList(const [0x91, 0xcc, 0x5c, 0xfe, 0xfa, 0x86, 0x32, 0xd4, 0xe3, 0xb2, 0x9d, 0x74, 0x3b, 0xda, 0x65, 0x10, 0x92, 0x13, 0x31, 0xbc, 0x14, 0x65, 0x5e, 0x93, 0x26, 0x94, 0x83, 0xbc, 0xfa, 0xc3, 0xb1, 0xe4, 0xce, 0x4d, 0x7b, 0x71, 0x60, 0x4b, 0x65, 0x96, 0xb6, 0xb4, 0x5b, 0xdd, 0xf5, 0xd6]);
  static SecureString? _anotherKey_cache;

  static SecureString get anotherKey {
    return _anotherKey_cache ??= SecureString(
      ciphertext: _anotherKey_ct,
      iv: _anotherKey_iv,
      tag: _anotherKey_tag,
      fieldName: 'anotherKey',
      kid: _kid,
      packageName: _packageName,
      decryptor: _decrypt,
    );
  }

  // Internal derived key cache
  static Uint8List? _cachedKey;

  static Future<Uint8List> _getDerivedKey() async {
    if (_cachedKey != null) return _cachedKey!;
    
    // We do NOT use Isolate.run() here because cryptography_flutter delegates
    // to native OS APIs (CryptoKit/java.security) which run on their own background
    // threads and cannot be called from a plain Dart Isolate.
    // Native PBKDF2 is fast and will not block the Flutter UI thread.
    
    final crypto = Cryptography.instance;
    final pbkdf2 = crypto.pbkdf2(
      macAlgorithm: Hmac.sha256(),
      iterations: 310000,
      bits: 256,
    );
    
    final saltInput = "$_packageName|$_buildFlavor|$_kid";
    final saltHash = await crypto.sha256().hash(utf8.encode(saltInput));
    final salt = Uint8List.fromList(saltHash.bytes);
    
    final secretKey = await pbkdf2.deriveKey(secretKey: SecretKey(utf8.encode('fallback_zero_config_key')), nonce: salt);
    _cachedKey = Uint8List.fromList(await secretKey.extractBytes());
    return _cachedKey!;
  }

  static Future<String> _decrypt(
    Uint8List ciphertext,
    Uint8List iv,
    Uint8List tag,
    String fieldName,
    String kid,
    String packageName,
  ) async {
    final key = await _getDerivedKey();
    final algorithm = AesGcm.with256bits(nonceLength: 12);
    final secretKey = SecretKey(key);
    final aad = utf8.encode(fieldName);
    final secretBox = SecretBox(ciphertext, nonce: iv, mac: Mac(tag));
    try {
      final decryptedBytes = await algorithm.decrypt(secretBox, secretKey: secretKey, aad: aad);
      return utf8.decode(decryptedBytes);
    } catch (e) {
      throw VaultDecryptionException('Failed to decrypt secret or tag authentication failed.');
    }
  }
}
