// GENERATED BY envault CLI — DO NOT EDIT
// KID: v1
// Password fingerprint: 6d837fa03d17730b (first 8 bytes of HMAC-SHA256)
// WARNING: Commit this file — it contains only ciphertext, never plaintext.
// Run "envault generate" to regenerate after changing .env or rotating password.
// ignore_for_file: non_constant_identifier_names, unused_field, unused_element, invalid_use_of_internal_member

part of 'vault.dart';

final class _Vault {
  // Key derivation parameters (non-secret AAD components)
  static const String _kid = 'v1';
  static const String _packageName = 'com.example.envault';
  static const String _buildFlavor = 'demo';

  // Password fingerprint — first 8 bytes of HMAC-SHA256(password, "ENVAULT_FINGERPRINT_V1").
  // Used by assertVaultPassword() to detect a password mismatch at app startup.
  // This is NOT the master password and cannot be reversed to recover it.
  static const String _passwordFingerprint = '6d837fa03d17730b';

  // Encrypted field: apiKey
  static final Uint8List _apiKey_iv = Uint8List.fromList(const [0xb2, 0x89, 0x14, 0x64, 0xea, 0x74, 0x7b, 0xb3, 0x52, 0x48, 0x55, 0x44]);
  static final Uint8List _apiKey_tag = Uint8List.fromList(const [0x0e, 0xa2, 0x5c, 0xe6, 0xa2, 0x3e, 0xf7, 0xbb, 0x05, 0xd4, 0x89, 0xbe, 0xe0, 0xdd, 0x56, 0xd3]);
  static final Uint8List _apiKey_ct = Uint8List.fromList(const [0x44, 0x69, 0x83, 0xdd, 0x60, 0xbd, 0xf3, 0x35, 0xd3, 0x62, 0x7d, 0xf8, 0x2f, 0x71, 0x5f, 0x6f, 0x6c, 0xad, 0x73, 0x0f, 0x89, 0x43, 0x17, 0xa9, 0xc2, 0xce, 0x16, 0xca, 0x94, 0x66, 0x10, 0x70, 0xb0, 0x5c, 0xda, 0x06, 0x67, 0x66, 0xa1, 0x6b, 0xb3, 0x08, 0x91, 0x94]);
  static SecureString? _apiKey_cache;

  static SecureString get apiKey {
    return _apiKey_cache ??= SecureString(
      ciphertext: _apiKey_ct,
      iv: _apiKey_iv,
      tag: _apiKey_tag,
      fieldName: 'apiKey',
      kid: _kid,
      packageName: _packageName,
      decryptor: _decrypt,
    );
  }

  // Encrypted field: anotherKey
  static final Uint8List _anotherKey_iv = Uint8List.fromList(const [0x2b, 0x37, 0xfd, 0xa4, 0x97, 0xfb, 0x75, 0xa8, 0xa9, 0xe9, 0x1a, 0x4b]);
  static final Uint8List _anotherKey_tag = Uint8List.fromList(const [0x90, 0xab, 0xdb, 0x00, 0xae, 0xa9, 0xb4, 0x94, 0x1f, 0xe7, 0x91, 0xbc, 0x29, 0xdb, 0xbd, 0xea]);
  static final Uint8List _anotherKey_ct = Uint8List.fromList(const [0x07, 0xb7, 0x9e, 0x69, 0x41, 0xa5, 0xac, 0x40, 0xcb, 0xc4, 0x03, 0xde, 0x29, 0xb4, 0xeb, 0x1f, 0xb1, 0x7c, 0x0c, 0xd1, 0x32, 0x57, 0xfe, 0x7d, 0x5e, 0x57, 0xb5, 0x18, 0xe9, 0x32, 0x75, 0x4b, 0x8b, 0x99, 0x39, 0x9e, 0x33, 0x68, 0x0b, 0x91, 0x32, 0xfb]);
  static SecureString? _anotherKey_cache;

  static SecureString get anotherKey {
    return _anotherKey_cache ??= SecureString(
      ciphertext: _anotherKey_ct,
      iv: _anotherKey_iv,
      tag: _anotherKey_tag,
      fieldName: 'anotherKey',
      kid: _kid,
      packageName: _packageName,
      decryptor: _decrypt,
    );
  }

  static Uint8List? _cachedKey;

  /// Verifies the VAULT_MASTER_PASSWORD baked into this binary matches
  /// the password used when running "envault generate".
  ///
  /// Call this once in main() before runApp():
  ///   await assertVaultPassword();
  ///
  /// Throws [VaultConfigurationException] if:
  ///   - VAULT_MASTER_PASSWORD was not set via --dart-define at build time.
  ///   - The password used in flutter build differs from the one used in envault generate.
  static Future<void> assertVaultPassword() async {
    const masterPassword = String.fromEnvironment('VAULT_MASTER_PASSWORD');
    if (masterPassword.isEmpty) {
      throw VaultConfigurationException(
        'VAULT_MASTER_PASSWORD is not set.\n'
        'Build your app with:\n'
        '  flutter run --dart-define=VAULT_MASTER_PASSWORD=<YOUR_SECRET>\n'
        '  flutter build apk --dart-define=VAULT_MASTER_PASSWORD=<YOUR_SECRET>\n'
        'Run "envault keygen" to generate a secure password.',
      );
    }
    final hmac = Hmac.sha256();
    final mac = await hmac.calculateMac(
      utf8.encode(masterPassword),
      secretKey: SecretKey(utf8.encode('ENVAULT_FINGERPRINT_V1')),
    );
    final runtimeFingerprint = mac.bytes
        .take(8)
        .map((b) => b.toRadixString(16).padLeft(2, '0'))
        .join();
    if (runtimeFingerprint != _passwordFingerprint) {
      throw VaultConfigurationException(
        'VAULT_MASTER_PASSWORD mismatch detected.\n'
        'The password used in "flutter build" differs from the one used in "envault generate".\n'
        'Fix: Run "envault generate" and "flutter build" with the SAME VAULT_MASTER_PASSWORD.\n'
        'Expected fingerprint: $_passwordFingerprint, Got: $runtimeFingerprint',
      );
    }
  }

  static Future<Uint8List> _getDerivedKey() async {
    if (_cachedKey != null) return _cachedKey!;

    // VAULT_MASTER_PASSWORD is injected at compile time via --dart-define.
    // It is NEVER a string literal in source code or version control.
    const masterPassword = String.fromEnvironment('VAULT_MASTER_PASSWORD');

    // assertVaultPassword() in main() would have already caught an empty/wrong
    // password. This is a defensive guard for the lazy-decryption path.
    if (masterPassword.isEmpty) {
      throw VaultConfigurationException(
        'VAULT_MASTER_PASSWORD is not set. '
        'Build with --dart-define=VAULT_MASTER_PASSWORD=<YOUR_SECRET>.',
      );
    }

    // Offload to OS-native crypto (CryptoKit/java.security) via cryptography_flutter.
    // 310,000 iterations of PBKDF2-HMAC-SHA256 per NIST SP 800-132 (2023 guidance).
    // This runs on a native thread — the Flutter UI thread is NOT blocked.
    final crypto = Cryptography.instance;
    final pbkdf2 = crypto.pbkdf2(
      macAlgorithm: Hmac.sha256(),
      iterations: 310000,
      bits: 256,
    );

    final saltInput = "$_packageName|$_buildFlavor|$_kid";
    final saltHash = await crypto.sha256().hash(utf8.encode(saltInput));
    final salt = Uint8List.fromList(saltHash.bytes);

    final secretKey = await pbkdf2.deriveKey(
      secretKey: SecretKey(utf8.encode(masterPassword)),
      nonce: salt,
    );
    _cachedKey = Uint8List.fromList(await secretKey.extractBytes());
    return _cachedKey!;
  }

  static Future<String> _decrypt(
    Uint8List ciphertext,
    Uint8List iv,
    Uint8List tag,
    String fieldName,
    String kid,
    String packageName,
  ) async {
    final key = await _getDerivedKey();
    final algorithm = AesGcm.with256bits(nonceLength: 12);
    final secretKey = SecretKey(key);
    final aad = utf8.encode(fieldName);
    final secretBox = SecretBox(ciphertext, nonce: iv, mac: Mac(tag));
    try {
      final decryptedBytes = await algorithm.decrypt(secretBox, secretKey: secretKey, aad: aad);
      return utf8.decode(decryptedBytes);
    } catch (e) {
      throw VaultDecryptionException('AES-GCM decryption failed for field "$fieldName". This typically means the master password is wrong or the ciphertext has been tampered with.');
    }
  }
}

/// Top-level function — call once in main() before runApp().
///
/// Detects a password mismatch between:
///   - The password used in "envault generate" (stored as fingerprint in this file)
///   - The password baked in via --dart-define=VAULT_MASTER_PASSWORD at build time
///
/// Example:
///   void main() async {
///     await assertVaultPassword();   // crashes clearly if mismatch
///     runApp(const MyApp());
///   }
Future<void> assertVaultPassword() => _Vault.assertVaultPassword();
