// GENERATED BY envault CLI — DO NOT EDIT
// KID: v1
// Password fingerprint: 6d837fa03d17730b (first 8 bytes of HMAC-SHA256)
// WARNING: Commit this file — it contains only ciphertext, never plaintext.
// Run "envault generate" to regenerate after changing .env or rotating password.
// ignore_for_file: non_constant_identifier_names, unused_field, unused_element, invalid_use_of_internal_member

part of 'vault.dart';

final class _Vault {
  // Key derivation parameters (non-secret AAD components)
  static const String _kid = 'v1';
  static const String _packageName = 'com.example.envault';
  static const String _buildFlavor = 'demo';

  // Password fingerprint — first 8 bytes of HMAC-SHA256(password, "ENVAULT_FINGERPRINT_V1").
  // Used by assertVaultPassword() to detect a password mismatch at app startup.
  // This is NOT the master password and cannot be reversed to recover it.
  static const String _passwordFingerprint = '6d837fa03d17730b';

  // Encrypted field: apiKey
  static final Uint8List _apiKey_iv = Uint8List.fromList(const [0xfb, 0x36, 0x1d, 0xb6, 0x09, 0x4a, 0xe0, 0x45, 0xa2, 0xc0, 0x4b, 0x8b]);
  static final Uint8List _apiKey_tag = Uint8List.fromList(const [0x0a, 0x87, 0x07, 0x4b, 0xfd, 0xbd, 0x8f, 0x3a, 0x55, 0xce, 0x15, 0x9e, 0xbd, 0x7b, 0x23, 0x31]);
  static final Uint8List _apiKey_ct = Uint8List.fromList(const [0xa6, 0x0f, 0xa5, 0x16, 0x5b, 0x32, 0x1c, 0x6d, 0x7c, 0xe6, 0x31, 0xf1, 0x8b, 0x77, 0x19, 0xc7, 0x2c, 0x6b, 0x33, 0xf6, 0xd7, 0x4f, 0xc1, 0x7f, 0x88, 0xe2, 0x8f, 0xad, 0x10, 0x51, 0xff, 0x55, 0xd2, 0x23, 0x37, 0xa6, 0x78, 0x62, 0xd7, 0xc7, 0x77, 0x37, 0x9b, 0x4e]);
  static SecureString? _apiKey_cache;

  static SecureString get apiKey {
    return _apiKey_cache ??= SecureString(
      ciphertext: _apiKey_ct,
      iv: _apiKey_iv,
      tag: _apiKey_tag,
      fieldName: 'apiKey',
      kid: _kid,
      packageName: _packageName,
      decryptor: _decrypt,
    );
  }

  // Encrypted field: anotherKey
  static final Uint8List _anotherKey_iv = Uint8List.fromList(const [0x3e, 0xbb, 0x36, 0xe4, 0x11, 0x79, 0x85, 0x9e, 0x51, 0xea, 0xac, 0xdd]);
  static final Uint8List _anotherKey_tag = Uint8List.fromList(const [0x66, 0x40, 0xdf, 0x28, 0x46, 0x7d, 0x4b, 0xae, 0xe4, 0xc6, 0x4d, 0xfd, 0xef, 0x98, 0x88, 0x37]);
  static final Uint8List _anotherKey_ct = Uint8List.fromList(const [0xe1, 0x3f, 0x45, 0xe0, 0x03, 0x88, 0x14, 0x21, 0xff, 0xca, 0xd8, 0x72, 0x07, 0xad, 0x2f, 0xbf, 0x44, 0x3e, 0x2e, 0x66, 0xaf, 0xd5, 0xee, 0x5b, 0x6b, 0x6f, 0x1c, 0x99, 0xf2, 0x9d, 0x58, 0xda, 0x7d, 0xf8, 0xbc, 0x0e, 0x56, 0x43, 0x13, 0x83, 0xff, 0x47]);
  static SecureString? _anotherKey_cache;

  static SecureString get anotherKey {
    return _anotherKey_cache ??= SecureString(
      ciphertext: _anotherKey_ct,
      iv: _anotherKey_iv,
      tag: _anotherKey_tag,
      fieldName: 'anotherKey',
      kid: _kid,
      packageName: _packageName,
      decryptor: _decrypt,
    );
  }

  static Uint8List? _cachedKey;

  /// Verifies the VAULT_MASTER_PASSWORD baked into this binary matches
  /// the password used when running "envault generate".
  ///
  /// Call this once in main() before runApp():
  ///   await assertVaultPassword();
  ///
  /// Throws [VaultConfigurationException] if:
  ///   - VAULT_MASTER_PASSWORD was not set via --dart-define at build time.
  ///   - The password used in flutter build differs from the one used in envault generate.
  static Future<void> assertVaultPassword() async {
    const masterPassword = String.fromEnvironment('VAULT_MASTER_PASSWORD');
    if (masterPassword.isEmpty) {
      throw VaultConfigurationException(
        'VAULT_MASTER_PASSWORD is not set.\n'
        'Build your app with:\n'
        '  flutter run --dart-define=VAULT_MASTER_PASSWORD=$YOUR_SECRET\n'
        '  flutter build apk --dart-define=VAULT_MASTER_PASSWORD=$YOUR_SECRET\n'
        'Run "envault keygen" to generate a secure password.',
      );
    }
    final hmac = Hmac.sha256();
    final mac = await hmac.calculateMac(
      utf8.encode(masterPassword),
      secretKey: SecretKey(utf8.encode('ENVAULT_FINGERPRINT_V1')),
    );
    final runtimeFingerprint = mac.bytes
        .take(8)
        .map((b) => b.toRadixString(16).padLeft(2, '0'))
        .join();
    if (runtimeFingerprint != _passwordFingerprint) {
      throw VaultConfigurationException(
        'VAULT_MASTER_PASSWORD mismatch detected.\n'
        'The password used in "flutter build" differs from the one used in "envault generate".\n'
        'Fix: Run "envault generate" and "flutter build" with the SAME VAULT_MASTER_PASSWORD.\n'
        'Expected fingerprint: $_passwordFingerprint, Got: $runtimeFingerprint',
      );
    }
  }

  static Future<Uint8List> _getDerivedKey() async {
    if (_cachedKey != null) return _cachedKey!;

    // VAULT_MASTER_PASSWORD is injected at compile time via --dart-define.
    // It is NEVER a string literal in source code or version control.
    const masterPassword = String.fromEnvironment('VAULT_MASTER_PASSWORD');

    // assertVaultPassword() in main() would have already caught an empty/wrong
    // password. This is a defensive guard for the lazy-decryption path.
    if (masterPassword.isEmpty) {
      throw VaultConfigurationException(
        'VAULT_MASTER_PASSWORD is not set. '
        'Build with --dart-define=VAULT_MASTER_PASSWORD=$YOUR_SECRET.',
      );
    }

    // Offload to OS-native crypto (CryptoKit/java.security) via cryptography_flutter.
    // 310,000 iterations of PBKDF2-HMAC-SHA256 per NIST SP 800-132 (2023 guidance).
    // This runs on a native thread — the Flutter UI thread is NOT blocked.
    final crypto = Cryptography.instance;
    final pbkdf2 = crypto.pbkdf2(
      macAlgorithm: Hmac.sha256(),
      iterations: 310000,
      bits: 256,
    );

    final saltInput = "$_packageName|$_buildFlavor|$_kid";
    final saltHash = await crypto.sha256().hash(utf8.encode(saltInput));
    final salt = Uint8List.fromList(saltHash.bytes);

    final secretKey = await pbkdf2.deriveKey(
      secretKey: SecretKey(utf8.encode(masterPassword)),
      nonce: salt,
    );
    _cachedKey = Uint8List.fromList(await secretKey.extractBytes());
    return _cachedKey!;
  }

  static Future<String> _decrypt(
    Uint8List ciphertext,
    Uint8List iv,
    Uint8List tag,
    String fieldName,
    String kid,
    String packageName,
  ) async {
    final key = await _getDerivedKey();
    final algorithm = AesGcm.with256bits(nonceLength: 12);
    final secretKey = SecretKey(key);
    final aad = utf8.encode(fieldName);
    final secretBox = SecretBox(ciphertext, nonce: iv, mac: Mac(tag));
    try {
      final decryptedBytes = await algorithm.decrypt(secretBox, secretKey: secretKey, aad: aad);
      return utf8.decode(decryptedBytes);
    } catch (e) {
      throw VaultDecryptionException('AES-GCM decryption failed for field "$fieldName". This typically means the master password is wrong or the ciphertext has been tampered with.');
    }
  }
}

/// Top-level function — call once in main() before runApp().
///
/// Detects a password mismatch between:
///   - The password used in "envault generate" (stored as fingerprint in this file)
///   - The password baked in via --dart-define=VAULT_MASTER_PASSWORD at build time
///
/// Example:
///   void main() async {
///     await assertVaultPassword();   // crashes clearly if mismatch
///     runApp(const MyApp());
///   }
Future<void> assertVaultPassword() => _Vault.assertVaultPassword();
